=== knu-3-velychko/OOP/Lab2/src/main/resources/DiamondFund.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

    <xs:simpleType name="preciousnessRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Precious"/>
            <xs:enumeration value="Semiprecious"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="percent">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="100.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cutTypeRestriction">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="4"/>
            <xs:maxInclusive value="15"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="valueRestriction">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="gems">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gem" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>

                            <xs:element name="preciousness">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="preciousnessRestriction"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="origin" type="xs:string"/>

                            <xs:element name="visual-parameters">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="color" type="xs:string"/>

                                        <xs:element name="opacity">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="percent"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="cut-type">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="cutTypeRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="value">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="valueRestriction"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== knu-3-velychko/OOP/Lab2/src/main/resources/DiamondFund.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="DiamondFund.xsd">
    <gem id="id1">
        <name>Ruby</name>
        <preciousness>Precious</preciousness>
        <origin>South Asia</origin>
        <visual-parameters>
            <color>green</color>
            <opacity>50.0</opacity>
            <cut-type>12</cut-type>
        </visual-parameters>
        <value>2.0</value>
    </gem>

    <gem id="id2">
        <name>Emerald</name>
        <preciousness>Precious</preciousness>
        <origin>Columbia</origin>
        <visual-parameters>
            <color>green</color>
            <opacity>70.0</opacity>
            <cut-type>10</cut-type>
        </visual-parameters>
        <value>5.0</value>
    </gem>

    <gem id="id3">
        <name>Garnets</name>
        <preciousness>Semiprecious</preciousness>
        <origin>USA</origin>
        <visual-parameters>
            <color>red</color>
            <opacity>30.0</opacity>
            <cut-type>8</cut-type>
        </visual-parameters>
        <value>10.0</value>
    </gem>
</gems>
